**Array Creation Functions**

---


*   numpy.array
*   numpy.zeros
*   numpy.ones
*   numpy.empty
*   numpy.full
*   numpy.eye
*   numpy.arange
*   numpy.linspace
*   numpy.random.rand
*   numpy.random.randint





In [ ]:
#Importing numpy library as np
import numpy as np

#1. Creating an array with numpy
# Using np.array() method

arr1 = np.array([1,2,3]) # np.array([]) for single array
arr2 = np.array([[1,2,3],[2,3,5],[1,5,7]]) # np.array([[],[],[]]) for multi dimensional array
print(arr1)
print(arr2)

[1 2 3]
[[1 2 3]
 [2 3 5]
 [1 5 7]]


In [ ]:
#2. Creating an array filled with zeros
# Using np.zeros() method

arr3 = np.zeros((3,3)) # np.zeros((rows, columns))
print(arr3)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#3. Creating an array filled with ones
# Using np.ones() method

arr4 = np.ones((3,3)) # np.ones((rows, columns))
print(arr4)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
#4. Creating an array with empty values (garbage values), Not initialized
# Using np.empty() method

arr5 = np.empty((2,2)) # np.empty((rows, columns))
print(arr5)

[[4.98599305e-310 0.00000000e+000]
 [6.63610051e-310 6.63616366e-310]]


In [ ]:
#5. Creating an array with specific values
# Using np.full() method

arr6 = np.full((3,3),5) # np.full((rows, columns), value to fill array)
print(arr6)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [ ]:
#6. Creating an Identity matrix
# Using np.eye() method

arr7 = np.eye(3) # np.eye(matrix size)
print(arr7)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#7. Creating a range of array
# Using np.arange()

arr8 = np.arange(3) # np.arange(end element)--(0 to 2)
print(arr8)

arr9 = np.arange(0,5) # np.arange(start element, stop element) -- (0,1,2,3,4)
print(arr9)

arr10 = np.arange(0,10,2) # np.arange(start, stop, step)--(0,2,4,6,8)
print(arr10)

[0 1 2]
[0 1 2 3 4]
[0 2 4 6 8]


In [ ]:
#8. Creating an arry with equally splitted
# Using np.linspace() method

arr11 = np.linspace(2,10,5) # np.linspace(start, stop, steps to fill) (by default endpoint=True)
print(arr11)

arr12 = np.linspace(2,10,5, endpoint=True) # np.linspace(start, stop, steps to fill, include end value(endpoint=True))
print(arr12)

arr13 = np.linspace(2,10,4, endpoint=False) # np.linspace(start, stop, steps to fill, don't include end value(endpoint=False))
print(arr13)

[ 2.  4.  6.  8. 10.]
[ 2.  4.  6.  8. 10.]
[2. 4. 6. 8.]


In [ ]:
#9. Creating array with any random values
# Using np.random.rand() method

arr14 = np.random.rand(3,3) # np.random.rand(rows, columns)
print(arr14)

[[0.77151693 0.53109052 0.55984082]
 [0.67651661 0.74667702 0.98981942]
 [0.35125251 0.21593294 0.5018175 ]]


In [ ]:
#10. Creating array with integer random values in specific range with specific size
# Using np.random.randint() method

arr15 = np.random.randint(0,10,(4)) # np.random.randint(low end, high end, (size))-- 1D array
print(arr15)

arr16 = np.random.randint(0,10,(2,3)) # np.random.randint(low end, high end, (rows, columns))-- 2D array
print(arr16)

[0 3 6 0]
[[5 1 9]
 [3 5 7]]


**Array Manipulation Functions**

---

**Reshaping**

*   reshape
*   ravel

**Transposing**
*   transpose

**Joining Arrays**
*   concatenate
*   stack
*   hstack
*   vstack
*   dstack

**Splitting Arrays**
*   split
*   array_split
*   hsplit
*   vsplit
*   dsplit

**Adding Elements**
*   append
*   insert

**Removing Elements**
*   delete

**Copying/Viewing Arrays**
*   copy
*   view
*   copyto

**Flipping and Rolling Arrays**
*   flip
*   roll

**Repeating Elements**
*   repeat
*   tile




In [ ]:
import numpy as np
#1. Reshaping (reshape()):
# Creating an array and reshape that
arr17 = np.arange(1,10)
print(arr17.shape)
print(arr17)
print('-'*15)

# Reshape the given array (should be exact same size)
# Using np.reshape(size,size)
reshapedArr = arr17.reshape(3,3)
print("After Reshape : ")
print(reshapedArr)

(9,)
[1 2 3 4 5 6 7 8 9]
---------------
After Reshape : 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
import numpy as np
#2. Flattern (ravel())
# Creating an array and flattern that array
arr19 = np.random.randint(0,10,(3,3))
print(arr19)
print('-'*15)

#Flattern the given array in contiguous manner
# Using arr.ravel() method
flatternedArray = arr19.ravel()
print("After flatterned the given array : ")
print(flatternedArray)

[[8 9 2]
 [3 7 0]
 [2 0 8]]
---------------
After flatterned the given array : 
[8 9 2 3 7 0 2 0 8]


In [ ]:
#3. Transpose: (transpose())
# Creating an array and find the transpose for that
print("Given array")
arr18 = np.random.randint(0,10,(3,3))
print(arr18)
print('-'*15)

#Transpose of given array
# Using np.transpose(arr)
print("After Transposed the given array using transpose() method : ")
transposedArray = np.transpose(arr18)
print(transposedArray)

#Transpose of given array
# Using arr.T method
print('-'*15)
print("After Transposed the given array using arr.T method : ")
print(arr18.T)

Given array
[[6 7 5]
 [5 4 8]
 [6 9 3]]
---------------
After Transposed the given array using transpose() method : 
[[6 5 6]
 [7 4 9]
 [5 8 3]]
---------------
After Transposed the given array using arr.T method : 
[[6 5 6]
 [7 4 9]
 [5 8 3]]


In [ ]:
#4. Joining Arrays : (concatinate())
print("Given Arrays")
arr19 = np.array([[1,2],[3,4]])
arr20 = np.array([[5, 6]])
print(arr19)
print(arr20)
print("-"*15)
joinedArrays = np.concatenate((arr19,arr20)) # Joining arrays one after another (without axis)
print("After Joined without axis")
print(joinedArrays)

print("-"*15)
joinedArrays1 = np.concatenate((arr19,arr20), axis=0) # Joining arrays horizantally using axis (axis = 0 - horizantal)
print("After Joined with axis is 0")
print(joinedArrays1)

print("-"*15)
joinedArrays2 = np.concatenate((arr19,arr20.T),axis=1) # Joining arrays vertically after transpose of 2nd array using axis (axis = 1 - vertial)
print("After Joined with axis is 1 - after Transpose")
print(joinedArrays2)


Given Arrays
[[1 2]
 [3 4]]
[[5 6]]
---------------
After Joined without axis
[[1 2]
 [3 4]
 [5 6]]
---------------
After Joined with axis is 0
[[1 2]
 [3 4]
 [5 6]]
---------------
After Joined with axis is 1 - after Transpose
[[1 2 5]
 [3 4 6]]


In [ ]:
#5. Joining Arrays: (stack())  - Adding dimention falong the axis
print("Given Arrays")
arr21 = np.array([[1,2],[3,4]])
arr22 = np.array([[5, 6],[10,2]])
print(arr21)
print(arr22)

print("-"*15)
print("After Stacking the arrays without using axis")
stackedArrays = np.stack((arr21,arr22)) # Stack the arrays a using (stack()) - (without using axis - by default - axis is 0)
print(stackedArrays)

print("-"*15)
print("After Stacking the arrays using axis is 0")
stackedArrays1 = np.stack((arr21,arr22), axis=0) # Stack the arrays a using (stack()) - (with using axis is 0)
print(stackedArrays1)

print("-"*15)
print("After Stacking the arrays using axis is 1")
stackedArrays2 = np.stack((arr21,arr22), axis=1) # Stack the arrays a using (stack()) - (with using axis is 1)
print(stackedArrays2)

Given Arrays
[[1 2]
 [3 4]]
[[ 5  6]
 [10  2]]
---------------
After Stacking the arrays without using axis
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [10  2]]]
---------------
After Stacking the arrays using axis is 0
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [10  2]]]
---------------
After Stacking the arrays using axis is 1
[[[ 1  2]
  [ 5  6]]

 [[ 3  4]
  [10  2]]]


In [ ]:
#6. Joining Arrays: (hstack()  - horizantally (column wise) and vstack() - vertically (row wise) and dstack() - in another axis ( depth wise )
print("Given Arrays")
arr23 = np.array([[1,2],[3,4]])
arr24 = np.array([[5, 6],[10,2]])
print(arr23)
print(arr24)

print("-"*15)
print("After joining arrays using hstack - horizantally")
h_stack = np.hstack((arr23, arr24)) # Joining arrays horizantally using hstack()
print(h_stack)

print("-"*15)
print("After joining arrays using vstack - vertically")
v_stack = np.vstack((arr23, arr24)) # Joining arrays vertically using vstack()
print(v_stack)

print("-"*15)
print("After joining arrays using dstack - vertically")
d_stack = np.dstack((arr23, arr24)) # Joining arrays depth wise in another axis using dstack()
print(d_stack)

Given Arrays
[[1 2]
 [3 4]]
[[ 5  6]
 [10  2]]
---------------
After joining arrays using hstack - horizantally
[[ 1  2  5  6]
 [ 3  4 10  2]]
---------------
After joining arrays using vstack - vertically
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [10  2]]
---------------
After joining arrays using dstack - vertically
[[[ 1  5]
  [ 2  6]]

 [[ 3 10]
  [ 4  2]]]


In [ ]:
#7. Splitting Arrays: (split()) - spli an array into multiple subarrays - array must be equal size
print("Given Array")
arr25 = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr25)

print("-"*15)
print("After splitting arrays using split")
splittedArrays = np.split(arr25, 5) # split array in sub arrays split(arr, sub arrays count) - necessary to be equal size array
print(splittedArrays)

Given Array
[ 1  2  3  4  5  6  7  8  9 10]
---------------
After splitting arrays using split
[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10])]


In [ ]:
#8. Splitting Arrays: (array_split()) - spli an array into multiple subarrays - array no need to be equal size
print("Given Array")
arr26 = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr26)

print("-"*15)
print("After splitting arrays using split")
splittedArrays1 = np.array_split(arr26, 3) # split array in sub arrays split(arr, sub arrays count) -not necessary to be equal size array
print(splittedArrays1)

Given Array
[ 1  2  3  4  5  6  7  8  9 10]
---------------
After splitting arrays using split
[array([1, 2, 3, 4]), array([5, 6, 7]), array([ 8,  9, 10])]


In [ ]:
#9. Splitting Arrays: using (hsplit() - horizantally (column wise) , vsplit() - vertically (row wise) and dsplit() - another axis (depth wise))
print("Given Array")
arr27 = np.array([1,2,3,4,5,6,7,8,9,10])
print(arr27)

print("-"*15)
print("After splitting the array using hsplit")
h_split = np.hsplit(arr27, 5) # Splitting array using hsplit() - size must be equal
print(h_split)

arr28 = np.array([[1,2,3,4],[5,6,7,8]])
print("-"*15)
print("After splitting the array using vsplit")
v_split = np.vsplit(arr28, 2) # Splitting array using vsplit() - size must be equal and also only works for 2 or more dimensions
print(v_split)

arr29 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("-"*15)
print("After splitting the array using dsplit")
d_split = np.dsplit(arr29, 2) # Splitting array using dsplit() - size must be equal and also only works for 2 or more dimensions
print(d_split)

Given Array
[ 1  2  3  4  5  6  7  8  9 10]
---------------
After splitting the array using hsplit
[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10])]
---------------
After splitting the array using vsplit
[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]
---------------
After splitting the array using dsplit
[array([[[1],
        [3]],

       [[5],
        [7]]]), array([[[2],
        [4]],

       [[6],
        [8]]])]


In [ ]:
#10. Adding/ Removing elements from array using (append, insert, delete)
print("Given Array")
arr30 = np.array([1,2,3])
print(arr30)

print("-"*15)
print("After appending an array elements to the given array")
appendedArray = np.append(arr30,[4,5,6]) # Adding elements in given array using append(arr, new array)
print(appendedArray)

print("-"*15)
print("After inserting an array elements to the given array")
insertedArray = np.insert(arr30, 1, [10, 11]) # Adding elements in given array using inster(arr,from index, new array)
print(insertedArray)

print("-"*15)
print("After deleting array elements from the given array")
deletedArray = np.delete(insertedArray, [0,1]) # Deleting  elements from given array using delete(arr,indexes of elements)
print(deletedArray)

Given Array
[1 2 3]
---------------
After appending an array elements to the given array
[1 2 3 4 5 6]
---------------
After inserting an array elements to the given array
[ 1 10 11  2  3]
---------------
After deleting array elements from the given array
[11  2  3]


In [ ]:
#11. Copying Elements - Using (copy() , view() and copyto())
print("Given array")
arr31 = np.array([1, 2, 3])
print(arr31)

print("-"*15)
print("After Copying the array using copy")
copiedArray = np.copy(arr31) # copying the Array using copy() method - Any modifications to the copy will not affect the original array, and vice versa
print(copiedArray)

print("-"*15)
print("After creating the new view of the array using view with the same data")
viewdArray = arr31.view() # creating the view for the given array with the same data - any modification to the original view will effect original array, and vice versa
print(viewdArray)

print("-"*15)
arr32 = np.array([1,2,3])
arr33 = np.array([4,5,6])
print("Before Copying ")
print(arr32)
print(arr33)
print("After copying one array to another array using copyto ")
np.copyto(arr32, arr33) # copying elements from one array to another array using np.copyto(array taking elements, copying array)
print(arr32 ,  "- copied from 2nd array")
print(arr33)

Given array
[1 2 3]
---------------
After Copying the array using copy
[1 2 3]
---------------
After creating the new view of the array using view with the same data
[1 2 3]
---------------
Before Copying 
[1 2 3]
[4 5 6]
After copying one array to another array using copyto 
[4 5 6] - copied from 2nd array
[4 5 6]


In [ ]:
#12. Flipping and Rolling Arrays - Using (flip() and roll())
print("given array")
arr34 = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print(arr34)

print("-"*15)
print("After Flipping the array")
flippedArray = np.flip(arr34) # Reverse the order of elements in an array using flip(arr).
print(flippedArray)

print("-"*15)
print("After Rolling the array")
rolledArray = np.roll(arr34, 1, axis=1) # Roll array elements along a specified axis using roll(arr,no.of positions to shift, axis).
print(rolledArray)

given array
[[1 2 3]
 [4 5 6]
 [7 8 9]]
---------------
After Flipping the array
[[9 8 7]
 [6 5 4]
 [3 2 1]]
---------------
After Rolling the array
[[3 1 2]
 [6 4 5]
 [9 7 8]]


In [ ]:
#13. Repeating Elements - Using(repeat() and tile())
print("Given Array")
arr35 = np.array([1, 2, 3])
print(arr35)

print("-"*15)
print("After repeatig array with repeat")
repeatedArray = np.repeat(arr35, 3) # Repeating array using repeat(arr, no. of times each element should repeat )
print(repeatedArray)

print("-"*15)
print("After repeatig array with tile")
tiledArray = np.tile(arr35, 3) # Repeating array using tile(arr, no. of times the tile(entire array) should repeat )
print(tiledArray)

Given Array
[1 2 3]
---------------
After repeatig array with repeat
[1 1 1 2 2 2 3 3 3]
---------------
After repeatig array with tile
[1 2 3 1 2 3 1 2 3]


**Array Mathematical Functions**

---

**Arithmetic Functions**

*   Addition (add)
*   Subtraction (subtract)
*   Multiplication (multiply)
*   Division (divide)
*   Power (power)
*   Modulus (mod)
*   Squareroot (sqrt)
*   Absolute (absolute)

**Trigonometric Functions**
*   Sin (sin)
*   Cos (cos)
*   Tan (tan)
*   Inverse Sin (arcsin)
*   Inverse Cos (arccos)
*   Inverse Tan (arctan)
*   Radians to Degrees (degrees)
*   Degrees to Radians (radians)

**Rounding Functions**
*   Round (round)
*   Floor (floor)
*   Ciel (ceil)

In [ ]:
# Arithmatic Functions
# Creating arrays for Arithmatic Operations
import numpy as np
print("Given Arrays")
arr37 = np.array([[4, 10, 18],[12,5,23]])
arr38 = np.array([[4, 5, 6],[4,2,9]])
print(arr37)
print(arr38)
print("-"*15)

#1. Addition using add()
addition = np.add(arr37, arr38) # np.add(arr1, arr1)
print("Addition : ")
print(addition)
print("-"*15)

#2. Subtraction using subtract()
subtraction = np.subtract(arr37, arr38) # np.subtract(arr1, arr1)
print("Subtraction : ")
print(subtraction)
print("-"*15)

#3. Multiplication using multiply()
multiplication = np.multiply(arr37, arr38) # np.multiply(arr1, arr1)
print("Multiplication : ")
print(multiplication)
print("-"*15)

#4. Division using divide()
division = np.divide(arr37, arr38) # np.divide(arr1, arr1)
print("Division : ")
print(division)

#5. Power of every element in array using power()
power = np.power(arr37, 2) # np.power(arr, value for power)
print("Power : ")
print(power)

#6. Modulus (remainder) using mod()
modulus = np.mod(arr37, arr38) # np.mod(arr1, arr2)
print("Modulus : ")
print(modulus)

#7. Square root of each element in array using sqrt()
squareRoot = np.sqrt(arr37) # np.sqrt(arr1)
print("Square Root : ")
print(squareRoot)

#8. Absolute of each element in array using absolute()
print("-"*15)
print("Before Absolute")
arr39 = np.array([-1,-2,-3,-4])
print(arr39)
print("-"*15)
absolute = np.absolute(arr39) # np.absolute(arr)
print("After Absolute : ")
print(absolute)

Given Arrays
[[ 4 10 18]
 [12  5 23]]
[[4 5 6]
 [4 2 9]]
---------------
Addition : 
[[ 8 15 24]
 [16  7 32]]
---------------
Subtraction : 
[[ 0  5 12]
 [ 8  3 14]]
---------------
Multiplication : 
[[ 16  50 108]
 [ 48  10 207]]
---------------
Division : 
[[1.         2.         3.        ]
 [3.         2.5        2.55555556]]
Power : 
[[ 16 100 324]
 [144  25 529]]
Modulus : 
[[0 0 0]
 [0 1 5]]
Square Root : 
[[2.         3.16227766 4.24264069]
 [3.46410162 2.23606798 4.79583152]]
---------------
Before Absolute
[-1 -2 -3 -4]
---------------
After Absolute : 
[1 2 3 4]


In [ ]:
# Trigonometric Functions
# Creating angle using np.pi (pi radians = 180 degrees)
print("Given Angle in radians :")
angle1 = np.pi / 2
print(angle1)
print("Given Angle in degrees :")
angle1Degrees = np.degrees(angle1) # converting radins to degrees using np.degrees(angle)
print(angle1Degrees)
print("-"*15)

#1. Sin using sin()
sinValue = np.sin(angle1) # sin(angle(in radians))
print("Sin for",angle1Degrees, "Degrees")
print(round(sinValue))
print("-"*15)

#2. Cos using cos()
cosValue = np.cos(angle1) # cos(angle(in radians))
print("Cos for",angle1Degrees, "Degrees")
print(round(cosValue))
print("-"*15)

#3. Tan using tan()
angle2 = np.pi/4
tanValue = np.tan(angle2) # tan(angle(in radians))
angle2Degrees = np.degrees(angle2) # converting radins to degrees using np.degrees(angle)
print("Tan for",angle2Degrees, "Degrees")
print(round(tanValue))
print("-"*15)

#4. Inverse Sin using arcsin()
print("Given Value is : ")
value1 = 1.0
print(value1)
inverseSin = np.arcsin(value1) #Inverse Sin-  arcsin(angle(in radians))
print("sin inverse of", value1)
print(np.degrees(inverseSin))
print("-"*15)

#5. Inverse Cos using arccos()
print("Given Value is : ")
value2 = -1.0
print(value2)
inverseCos = np.arccos(value2) #Inverse Cos-  arccos(angle(in radians))
print("cos inverse of", value2)
print(np.degrees(inverseCos))
print("-"*15)

#6. Inverse Tan using arctan()
print("Given Value is : ")
value3 = 1.0
print(value3)
inverseTan = np.arctan(value3) #Inverse Tan-  arctan(angle(in radians))
print("tan inverse of", value3)
print(np.degrees(inverseTan))
print("-"*15)

#7. Radians to Degrees conersion
angle_radians = np.pi
print("Angle in Radians :",angle_radians)
angle_degrees = np.degrees(angle_radians) # converting radins to degrees using np.degrees(angle)
print("Angle in Degrees after Conversion :",angle_degrees)
print("-"*15)

#7. Degrees to Radians conersion
angle_degres1 = 180.0
print("Angle in Degrees :",angle_degres1)
angle_radians1 = np.radians(angle_degres1)  # converting degrees to radians using np.radians(angle)
print("Angle in Radians after Conversion :",angle_radians1)

Given Angle in radians :
1.5707963267948966
Given Angle in degrees :
90.0
---------------
Sin for 90.0 Degrees
1
---------------
Cos for 90.0 Degrees
0
---------------
Tan for 45.0 Degrees
1
---------------
Given Value is : 
1.0
sin inverse of 1.0
90.0
---------------
Given Value is : 
-1.0
cos inverse of -1.0
180.0
---------------
Given Value is : 
1.0
tan inverse of 1.0
45.0
---------------
Angle in Radians : 3.141592653589793
Angle in Degrees after Conversion : 180.0
---------------
Angle in Degrees : 180.0
Angle in Radians after Conversion : 3.141592653589793


**Array Statistical Functions**

---

*   Mean (mean)
*   Median (median)
*   Standard Deviation (std)
*   Variance (var)
*   Sum (sum)
*   Minimum (min)
*   Maximum (max)
*   Index of Minimum (argmin)
*   Index of Maximum (argmax)
*   nth Percentile (percentile)

In [1]:
# Array Statistical Functions
import numpy as np
#1. Mean of Array - mean()
print("Given Array")
arr40 = np.array([1,2,3,4,5])
print(arr40)
print("Mean of Array")
mean = np.mean(arr40) # np.mean(arr)
print(mean)
print("-"*15)

#2. Median of Array - median()
print("Given Array")
arr41 = np.array([1,2,5,7,8])
print(arr41)
print("-"*15)
print("Median of Array")
median = np.median(arr41) # np.median(arr)
print(median)
print("-"*15)

#3. Standrad Deviation of Array - std()
print("Given Array")
arr42 = np.array([1,2,3,4,5])
print(arr42)
print("Standard Deviation of Array")
standardDeviation = np.std(arr42) # np.std(arr)
print(standardDeviation)
print("-"*15)

#4. Variance of Array - var()
print("Given Array")
arr43 = np.array([1,2,3,4,5])
print(arr43)
print("Variance of Array")
variance = np.var(arr43) # np.var(arr)
print(variance)
print("-"*15)

#5. Sum of Array - sum()
print("Given Array")
arr44 = np.array([1,2,3,4,5])
print(arr44)
print("Sum of Array")
sum = np.sum(arr44) # np.sum(arr)
print(sum)
print("-"*15)

#6. Minimum of Array - min()
print("Given Array")
arr45 = np.array([5,2,45,4,1])
print(arr45)
print("Minimum of Array")
min = np.min(arr45) # np.min(arr)
print(min)
print("-"*15)

#7. Maximum of Array - max()
print("Given Array")
arr46 = np.array([5,2,45,4,1])
print(arr46)
print("Maximum of Array")
max = np.max(arr46) # np.max(arr)
print(max)
print("-"*15)

#8. Index of Minimum element in Array - argmin()
print("Given Array")
arr47 = np.array([5,2,45,4,1])
print(arr47)
print("Index of Minimum element in Array")
minIndex = np.argmin(arr47)  # np.argmin(arr)
print(minIndex)
print("-"*15)

#9. Index of Maximum element in Array - argmax()
print("Given Array")
arr48 = np.array([5,2,45,4,1])
print(arr48)
print("Index of Maximum element in Array")
maxIndex = np.argmax(arr48)  # np.argmax(arr)
print(maxIndex)
print("-"*15)

#10. nth percentile of Array - percentile()
print("Given Array")
arr49 = np.array([1,2,3,4,5])
print(arr49)
print("Percentile of Array")
percentile = np.percentile(arr49,30)  # np.percentile(arr, how much percentile you want (ex-30))
print(percentile)
print("-"*15)


Given Array
[1 2 3 4 5]
Mean of Array
3.0
---------------
Given Array
[1 2 5 7 8]
---------------
Median of Array
5.0
---------------
Given Array
[1 2 3 4 5]
Standard Deviation of Array
1.4142135623730951
---------------
Given Array
[1 2 3 4 5]
Variance of Array
2.0
---------------
Given Array
[1 2 3 4 5]
Sum of Array
15
---------------
Given Array
[ 5  2 45  4  1]
Minimum of Array
1
---------------
Given Array
[ 5  2 45  4  1]
Maximum of Array
45
---------------
Given Array
[ 5  2 45  4  1]
Index of Minimum element in Array
4
---------------
Given Array
[ 5  2 45  4  1]
Index of Maximum element in Array
2
---------------
Given Array
[1 2 3 4 5]
Percentile of Array
2.2
---------------


**Array Input and Output Functions**

---

*   Load data from txt file (loadtxt)
*   Load data from txt file, with missing values (genfromtxt)
*   Save an arry to the text file (savetxt)
*   Save an arry to the binary file (.npy) (save)
*    Save several arrays into a single file in compressed (.npz) (savez)
*   Load arrays or pickled objects from .npy, .npz, or pickled files (load)

In [30]:
# Array Input and Output Functions
import numpy as np
#1.  Load data from txt file (loadtxt) - only data should be numerical values
print("Load data from txt file : ")
data1 = np.loadtxt('loadtxt.txt') # np.loadtxt('filename with path if required')
print(data1)
print("-"*15)

#2. Load data from txt file, with missing values (genfromtxt)
print("Load data from txt file, with missing values : fill missing values (N/A) with -1 in below example")
data2 = np.genfromtxt('genfromtxt.txt', missing_values='N/A', filling_values=-1)
# np.genfromtxt('file name', missing_values='value', filling_values= value)
print(data2)
print("-"*15)

#3. Save an array to a text file (savetxt)
print("Save an array to a text file")
arrData1 = np.array([[1,2,3], [4,5,6]])
np.savetxt('savetxt.txt', arrData1)
print("Data Saved with file name savetxt.txt")
print("-"*15)

#4. Save an array to a binary file (.npy) (save):
print("Save an array to a binary file")
arrData2 = np.array([[5,3,4],[8,7,9]])
np.save('savedata.npy',arrData2)
print("Data saved with file name savedata.npy")
print("-"*15)

#5. Save several arrays into a single file in compressed format (.npz) (savez):
print(" Save several arrays into a single file in compressed format ")
data3 = np.array([5,6,7])
data4 = np.array([10,25,65])
np.savez('savez.npz', data1=data3, data2=data4)
print("Data saved with file name savez.npz")
print("-"*15)

#6. Load arrays or pickled objects from .npy, .npz, or pickled files (load):
print(" Load arrays or pickled objects from .npy, .npz, or pickled files (load)")
dataNpy = np.load('savedata.npy')
print("Loaded data from savedata.npy file")
print(dataNpy)
print("-"*15)

dataNpz = np.load('savez.npz')
print("Loaded data from savez.npz file")
print(dataNpz)
print("Loaded data1 :",dataNpz['data1'])
print("Loaded data2 :",dataNpz['data2'])
print("-"*15)



Load data from txt file : 
[ 12.  56.  89. 741. 256. 520.]
---------------
Load data from txt file, with missing values : fill missing values (N/A) with -1 in below example
[[ 1.  2.  3. -1.  5.]
 [ 4.  5.  6.  5. -1.]]
---------------
Save an array to a text file
Data Saved with file name savetxt.txt
---------------
Save an array to a binary file
Data saved with file name savedata.npy
---------------
 Save several arrays into a single file in compressed format 
Data saved with file name savez.npz
---------------
 Load arrays or pickled objects from .npy, .npz, or pickled files (load)
Loaded data from savedata.npy file
[[5 3 4]
 [8 7 9]]
---------------
Loaded data from savez.npz file
NpzFile 'savez.npz' with keys: data1, data2
Loaded data1 : [5 6 7]
Loaded data2 : [10 25 65]
---------------
