In [4]:
import numpy as np

#1. Creating an array with numpy
# Using np.array() method

arr1 = np.array([1,2,3]) # np.array([]) for single array
arr2 = np.array([[1,2,3],[2,3,5],[1,5,7]]) # np.array([[],[],[]]) for multi dimensional array
print(arr1)
print(arr2)

[1 2 3]
[[1 2 3]
 [2 3 5]
 [1 5 7]]


In [6]:
#2. Creating an array filled with zeros
# Using np.zeros() method

arr3 = np.zeros((3,3)) # np.zeros((rows, columns))
print(arr3)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
#3. Creating an array filled with ones
# Using np.ones() method

arr4 = np.ones((3,3)) # np.ones((rows, columns))
print(arr4)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [11]:
#4. Creating an array with empty values (garbage values), Not initialized
# Using np.empty() method

arr5 = np.empty((2,2)) # np.empty((rows, columns))
print(arr5)

[[4.98599305e-310 0.00000000e+000]
 [6.63610051e-310 6.63616366e-310]]


In [15]:
#5. Creating an array with specific values
# Using np.full() method

arr6 = np.full((3,3),5) # np.full((rows, columns), value to fill array)
print(arr6)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [20]:
#6. Creating an Identity matrix
# Using np.eye() method

arr7 = np.eye(3) # np.eye(matrix size)
print(arr7)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [24]:
#7. Creating a range of array
# Using np.arange()

arr8 = np.arange(3) # np.arange(end element)--(0 to 2)
print(arr8)

arr9 = np.arange(0,5) # np.arange(start element, stop element) -- (0,1,2,3,4)
print(arr9)

arr10 = np.arange(0,10,2) # np.arange(start, stop, step)--(0,2,4,6,8)
print(arr10)

[0 1 2]
[0 1 2 3 4]
[0 2 4 6 8]


In [33]:
#8. Creating an arry with equally splitted
# Using np.linspace() method

arr11 = np.linspace(2,10,5) # np.linspace(start, stop, steps to fill) (by default endpoint=True)
print(arr11)

arr12 = np.linspace(2,10,5, endpoint=True) # np.linspace(start, stop, steps to fill, include end value(endpoint=True))
print(arr12)

arr13 = np.linspace(2,10,4, endpoint=False) # np.linspace(start, stop, steps to fill, don't include end value(endpoint=False))
print(arr13)

[ 2.  4.  6.  8. 10.]
[ 2.  4.  6.  8. 10.]
[2. 4. 6. 8.]


In [41]:
#9. Creating array with any random values
# Using np.random.rand() method

arr14 = np.random.rand(3,3) # np.random.rand(rows, columns)
print(arr14)

[[0.77151693 0.53109052 0.55984082]
 [0.67651661 0.74667702 0.98981942]
 [0.35125251 0.21593294 0.5018175 ]]


In [51]:
#10. Creating array with integer random values in specific range with specific size
# Using np.random.randint() method

arr15 = np.random.randint(0,10,(4)) # np.random.randint(low end, high end, (size))-- 1D array
print(arr15)

arr16 = np.random.randint(0,10,(2,3)) # np.random.randint(low end, high end, (rows, columns))-- 2D array
print(arr16)

[0 3 6 0]
[[5 1 9]
 [3 5 7]]
